printWidth: 100 # デフォルトの行の長さを100文字に設定
tabWidth: 2 # タブ幅を2スペースに設定
overrides:
  - files: package.xml
    options:
      printWidth: 1000
      xmlSelfClosingSpace: false
      xmlWhitespaceSensitivity: ignore

  - files: "*.launch.xml"
    options:
      printWidth: 200
      xmlSelfClosingSpace: false
      xmlWhitespaceSensitivity: ignore

  - files: "*.xacro"
    options:
      printWidth: 200
      xmlSelfClosingSpace: false
      xmlWhitespaceSensitivity: ignore #
